name: riverpod_toast
description: A Riverpod-based toast notification system with overlay support, localization, and adaptive theming.
version: 0.1.0
homepage: https://www.kumpali.com
repository: https://github.com/sumitsharansatsangi/riverpod_toast/

topics:
  - toast
  - snackbar
  - riverpod
  - riverpod-toast
  - message
  - notification

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.16
  flutter_styled_toast: ^2.1.3
  easy_localization: ^3.0.5
  riverpod_annotation: ^3.0.0-dev.16

dev_dependencies:
  build_runner: any
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16